#!/bin/sh
cd ..
which sh
clear
echo = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
echo What do you want to do! [NOTE: PUT THE WRAPPER-OFFLINE FOLDER IN YOUR DESKTOP]
echo = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
echo 1 - Install HTTP-Server [click server folder then run the.crt or else it wont work]
echo 2 - Start Wrapper Offline [Put wrapper offline folder in your desktop or it wont work]
echo    



          while true; do
            read -p "Selection: " sel2
            case $sel2 in
                [1]* )
                clear
                echo = = = = = = = = = = = = = = = = = = = = 
                echo Downloading Wrapper Offline HTTP Server
                echo = = = = = = = = = = = = = = = = = = = =
                sudo npm install http-server -g &
                sleep 10
                clear
                
                
                
                
                echo  = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =  
                echo HTTP-SERVER has been installed! [or not] Now just  press 2. to run wrapper offline.
                echo  = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = 
                echo
              



               ;;
                [2]* )
                clear
                echo = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
                echo Starting Wrapper Offfline HTTP Server NOTE: You need to install the the.crt by clicking it
                echo = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
                open -a Terminal.app $HOME/desktop/wrapper-offline/autostart-http-server.sh
                
                echo = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
                echo Starting Wrapper Offline Node.js localhost
                echo = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = = =
                cd $HOME/desktop/wrapper-offline/wrapper
                npm start

               


            while [ true ]
                do
                   
                    read -r -p "you should not be in this screen unless something broke OR U DIDNT PUT WRAPPER OFFLINE ON YOUR  DESKTOP SO DO IT" key
                done
                ;;
                * ) echo "";;
            esac
        done
        ;;
        * );;
    esac
done
